# Generated by Django 3.2.7 on 2022-04-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUB', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='desc',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
