# Generated by Django 3.2.7 on 2022-04-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffees',
            name='add_in',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='add_ins',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
