# Generated by Django 3.2.7 on 2022-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HUB', '0003_auto_20220408_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffees',
            name='category',
            field=models.TextField(choices=[('Brewed Coffees', 'Brewed Coffees'), ('Espresso', 'Espresso'), ('Specialty Drinks', 'Specialty Drinks'), ('Blended Coffees', 'Blended Coffees')]),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.TextField(choices=[('Breakfast', 'Breakfast'), ('Salads', 'Salads'), ('Pastries & More', 'Pastries & More'), ('Sandwiches & Wraps', 'Sandwiches & Wraps')]),
        ),
    ]
