# Generated by Django 3.2.7 on 2022-05-04 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HUB', '0005_order_order_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_num',
        ),
    ]
