# Generated by Django 3.2.7 on 2022-05-04 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HUB', '0006_remove_order_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='order',
            name='is_paid_for',
            field=models.BooleanField(default=False),
        ),
    ]
